//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaiyuanshe.OpenHackathon.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kaiyuanshe.OpenHackathon.Server.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team &quot;{teamName}&quot; has a new member &quot;{memberName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_addTeamMember {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_addTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment request of user &quot;{enrolledUser}&quot; is approved by &quot;{adminName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_approveEnrollment {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_approveEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hackathon is approved by an admin and becomes online..
        /// </summary>
        internal static string ActivityLog_Hackathon_approveHackahton {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_approveHackahton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership request of user &quot;{memberName}&quot; to join team &quot;{teamName}&quot; is approved..
        /// </summary>
        internal static string ActivityLog_Hackathon_approveTeamMember {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_approveTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hackathon becomes ReadOnly..
        /// </summary>
        internal static string ActivityLog_Hackathon_archiveHackathon {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_archiveHackathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &apos;{adminName}&apos; published an announcement..
        /// </summary>
        internal static string ActivityLog_Hackathon_createAnnouncement {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_createAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new award &quot;{awardName}&quot; is created by &quot;{userName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_createAward {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_createAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{userName}&quot; is awarded &quot;{awardName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_createAwardAssignmentIndividual {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_createAwardAssignmentIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team &quot;{teamName}&quot; is awarded &quot;{awardName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_createAwardAssignmentTeam {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_createAwardAssignmentTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user enrolled successfully: {userName}.
        /// </summary>
        internal static string ActivityLog_Hackathon_createEnrollment {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_createEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{userName}&quot; created a new experiment on template &quot;{templateName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_createExperiment {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_createExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by user: {userName}..
        /// </summary>
        internal static string ActivityLog_Hackathon_createHackathon {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_createHackathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{adminUser}&quot; is added as an administrator by &quot;{userName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_createHackathonAdmin {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_createHackathonAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &apos;{userName}&apos; added a judge: &apos;{judgeName}&apos;.
        /// </summary>
        internal static string ActivityLog_Hackathon_createJudge {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_createJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{adminName}&quot; added an organizer &quot;{organizerName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_createOrganizer {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_createOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hackathon judge &quot;{judgeName}&quot; rated team &quot;{teamName}&quot; on kind &quot;{kindName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_createRating {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_createRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{userName}&quot; created a new rating kind: {ratingKind}..
        /// </summary>
        internal static string ActivityLog_Hackathon_createRatingKind {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_createRatingKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new team &apos;{teamName}&apos; is created by {userName}..
        /// </summary>
        internal static string ActivityLog_Hackathon_createTeam {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_createTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{userName}&quot; added a new work for team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_createTeamWork {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_createTeamWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{adminName}&quot; created a new template &quot;{templateName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_createTemplate {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_createTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{adminName}&quot; deleted an announcement..
        /// </summary>
        internal static string ActivityLog_Hackathon_deleteAnnouncement {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_deleteAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{adminName}&quot; removed award &quot;{awardName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_deleteAward {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_deleteAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An assignment on award &quot;{awardName}&quot; is revoked by &quot;{adminName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_deleteAwardAssignment {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_deleteAwardAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{adminName}&quot; deleted an experiment..
        /// </summary>
        internal static string ActivityLog_Hackathon_deleteExperiment {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_deleteExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted by user: {userName}.
        /// </summary>
        internal static string ActivityLog_Hackathon_deleteHackathon {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_deleteHackathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &apos;{userName}&apos; removed another admin &apos;{adminName}&apos;..
        /// </summary>
        internal static string ActivityLog_Hackathon_deleteHackathonAdmin {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_deleteHackathonAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge &apos;{judgeName}&apos; is deleted by admin &apos;{userName}&apos;.
        /// </summary>
        internal static string ActivityLog_Hackathon_deleteJudge {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_deleteJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{adminName}&quot; deleted an organizer &quot;{organizerName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_deleteOrganizer {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_deleteOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge &quot;{judgeName}&quot; removed a rating..
        /// </summary>
        internal static string ActivityLog_Hackathon_deleteRating {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_deleteRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{adminName}&quot; deleted rating kind &quot;{ratingKind}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_deleteRatingKind {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_deleteRatingKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team &quot;{teamName}&quot; dismissed by user &quot;{adminName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_deleteTeam {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_deleteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the admins removed member &quot;{memberName}&quot; from team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_deleteTeamMember {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_deleteTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A team work is removed from team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_deleteTeamWork {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_deleteTeamWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{adminName}&quot; deleted experiment template &quot;{templateName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_deleteTemplate {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_deleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{memberName}&quot; requested to join team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_joinTeam {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_joinTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &quot;{memberName}&quot; left team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_leaveTeam {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_leaveTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to go online, waiting for approval. Requested by: {userName}.
        /// </summary>
        internal static string ActivityLog_Hackathon_publishHackathon {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_publishHackathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment request of user &quot;{enrolledUser}&quot; is rejected by &quot;{adminName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_rejectEnrollment {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_rejectEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{userName}&quot; reset the experiment &quot;{experiment}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_resetExperiment {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_resetExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hackathon becomes Writable..
        /// </summary>
        internal static string ActivityLog_Hackathon_unarchiveHackathon {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_unarchiveHackathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{adminName}&quot; updated an announcement..
        /// </summary>
        internal static string ActivityLog_Hackathon_updateAnnouncement {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_updateAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{adminName}&quot; updated the award &quot;{awardName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_updateAward {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_updateAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{adminName}&quot; updated an assignment on award &quot;{awardName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_updateAwardAssignment {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_updateAwardAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment info of user &quot;{userName}&quot; updated..
        /// </summary>
        internal static string ActivityLog_Hackathon_updateEnrollment {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_updateEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated by user: {userName}..
        /// </summary>
        internal static string ActivityLog_Hackathon_updateHackathon {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_updateHackathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &apos;{userName}&apos; updated judge: &apos;{judgeName}&apos;.
        /// </summary>
        internal static string ActivityLog_Hackathon_updateJudge {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_updateJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{adminName}&quot; updated organizer &quot;{organizerName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_updateOrganizer {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_updateOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge &quot;{judgeName}&quot; updated a rating on kind &quot;{ratingKindName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_updateRating {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_updateRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{adminName}&quot; updated rating kind &quot;{ratingKind}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_updateRatingKind {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_updateRatingKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team &quot;{teamName}&quot; updated by user &quot;{adminName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_updateTeam {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_updateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info of member &quot;{memberName}&quot; in team &quot;{teamName}&quot; updated..
        /// </summary>
        internal static string ActivityLog_Hackathon_updateTeamMember {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_updateTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{adminName}&quot; updated the role of team member &quot;{memberName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_updateTeamMemberRole {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_updateTeamMemberRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team &quot;{teamName}&quot; updated a work..
        /// </summary>
        internal static string ActivityLog_Hackathon_updateTeamWork {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_updateTeamWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{adminName}&quot; updated the template &quot;{templateName}&quot;..
        /// </summary>
        internal static string ActivityLog_Hackathon_updateTemplate {
            get {
                return ResourceManager.GetString("ActivityLog_Hackathon_updateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited a new team member &quot;{memberName}&quot; by admin &quot;{adminName}&quot;..
        /// </summary>
        internal static string ActivityLog_Team_addTeamMember {
            get {
                return ResourceManager.GetString("ActivityLog_Team_addTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership request of user &quot;{memberName}&quot; is approved by &quot;{adminName}&quot;..
        /// </summary>
        internal static string ActivityLog_Team_approveTeamMember {
            get {
                return ResourceManager.GetString("ActivityLog_Team_approveTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team is awarded &quot;{awardName}&quot;..
        /// </summary>
        internal static string ActivityLog_Team_createAwardAssignmentTeam {
            get {
                return ResourceManager.GetString("ActivityLog_Team_createAwardAssignmentTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated on kind &quot;{kindName}&quot; by judge &quot;{judgeName}&quot;..
        /// </summary>
        internal static string ActivityLog_Team_createRating {
            get {
                return ResourceManager.GetString("ActivityLog_Team_createRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team created by &apos;{userName}&apos;..
        /// </summary>
        internal static string ActivityLog_Team_createTeam {
            get {
                return ResourceManager.GetString("ActivityLog_Team_createTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{userName}&quot; added a new work..
        /// </summary>
        internal static string ActivityLog_Team_createTeamWork {
            get {
                return ResourceManager.GetString("ActivityLog_Team_createTeamWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An assignment on award &quot;{awardName}&quot; is revoked by &quot;{adminName}&quot;..
        /// </summary>
        internal static string ActivityLog_Team_deleteAwardAssignment {
            get {
                return ResourceManager.GetString("ActivityLog_Team_deleteAwardAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team dismissed by user &quot;{adminName}&quot;..
        /// </summary>
        internal static string ActivityLog_Team_deleteTeam {
            get {
                return ResourceManager.GetString("ActivityLog_Team_deleteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed team member &quot;{memberName}&quot; or rejected the membership request..
        /// </summary>
        internal static string ActivityLog_Team_deleteTeamMember {
            get {
                return ResourceManager.GetString("ActivityLog_Team_deleteTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &quot;{memberName}&quot; deleted a team work..
        /// </summary>
        internal static string ActivityLog_Team_deleteTeamWork {
            get {
                return ResourceManager.GetString("ActivityLog_Team_deleteTeamWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{memberName}&quot; requested to join team..
        /// </summary>
        internal static string ActivityLog_Team_joinTeam {
            get {
                return ResourceManager.GetString("ActivityLog_Team_joinTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &quot;{memberName}&quot; left the team..
        /// </summary>
        internal static string ActivityLog_Team_leaveTeam {
            get {
                return ResourceManager.GetString("ActivityLog_Team_leaveTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin &quot;{adminName}&quot; updated an assignment on award &quot;{awardName}&quot;..
        /// </summary>
        internal static string ActivityLog_Team_updateAwardAssignment {
            get {
                return ResourceManager.GetString("ActivityLog_Team_updateAwardAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge &quot;{judgeName}&quot; updated the rating on kind &quot;{ratingKindName}&quot;..
        /// </summary>
        internal static string ActivityLog_Team_updateRating {
            get {
                return ResourceManager.GetString("ActivityLog_Team_updateRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team info updated by user &quot;{adminName}&quot;..
        /// </summary>
        internal static string ActivityLog_Team_updateTeam {
            get {
                return ResourceManager.GetString("ActivityLog_Team_updateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info of member &quot;{memberName}&quot; is updated..
        /// </summary>
        internal static string ActivityLog_Team_updateTeamMember {
            get {
                return ResourceManager.GetString("ActivityLog_Team_updateTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{adminName}&quot; updated the role of team member &quot;{memberName}&quot;..
        /// </summary>
        internal static string ActivityLog_Team_updateTeamMemberRole {
            get {
                return ResourceManager.GetString("ActivityLog_Team_updateTeamMemberRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &quot;{memberName}&quot; updated a team work..
        /// </summary>
        internal static string ActivityLog_Team_updateTeamWork {
            get {
                return ResourceManager.GetString("ActivityLog_Team_updateTeamWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Added a new memeber &quot;{memberName}&quot; to team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_addTeamMember {
            get {
                return ResourceManager.GetString("ActivityLog_User_addTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Added as a new member to team &quot;{teamName}&quot; by &quot;{adminName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_addTeamMember2 {
            get {
                return ResourceManager.GetString("ActivityLog_User_addTeamMember2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Approved enrollment of user &quot;{enrolledUser}&quot;..
        /// </summary>
        internal static string ActivityLog_User_approveEnrollment {
            get {
                return ResourceManager.GetString("ActivityLog_User_approveEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Enrollment approved by admin &quot;{adminName}&quot;.
        /// </summary>
        internal static string ActivityLog_User_approveEnrollment2 {
            get {
                return ResourceManager.GetString("ActivityLog_User_approveEnrollment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Approved and published hackathon..
        /// </summary>
        internal static string ActivityLog_User_approveHackahton {
            get {
                return ResourceManager.GetString("ActivityLog_User_approveHackahton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Approved membership request of user &quot;{memberName}&quot; to join team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_approveTeamMember {
            get {
                return ResourceManager.GetString("ActivityLog_User_approveTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Membership request to join team &quot;{teamName}&quot; is approved by &quot;{adminName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_approveTeamMember2 {
            get {
                return ResourceManager.GetString("ActivityLog_User_approveTeamMember2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Updated hackathon to ReadOnly..
        /// </summary>
        internal static string ActivityLog_User_archiveHackathon {
            get {
                return ResourceManager.GetString("ActivityLog_User_archiveHackathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Published an announcement..
        /// </summary>
        internal static string ActivityLog_User_createAnnouncement {
            get {
                return ResourceManager.GetString("ActivityLog_User_createAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Created a new award &quot;{awardName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_createAward {
            get {
                return ResourceManager.GetString("ActivityLog_User_createAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Awards &quot;{awardName}&quot; to &quot;{userName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_createAwardAssignmentIndividual {
            get {
                return ResourceManager.GetString("ActivityLog_User_createAwardAssignmentIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Awarded &quot;{awardName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_createAwardAssignmentIndividual2 {
            get {
                return ResourceManager.GetString("ActivityLog_User_createAwardAssignmentIndividual2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Awards &quot;{awardName}&quot; to &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_createAwardAssignmentTeam {
            get {
                return ResourceManager.GetString("ActivityLog_User_createAwardAssignmentTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]enrolled in hackathon..
        /// </summary>
        internal static string ActivityLog_User_createEnrollment {
            get {
                return ResourceManager.GetString("ActivityLog_User_createEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Created a new experiment on template &quot;{templateName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_createExperiment {
            get {
                return ResourceManager.GetString("ActivityLog_User_createExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Created a new hackathon: {hackathonName}.
        /// </summary>
        internal static string ActivityLog_User_createHackathon {
            get {
                return ResourceManager.GetString("ActivityLog_User_createHackathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Created or updated an admin &quot;{adminName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_createHackathonAdmin {
            get {
                return ResourceManager.GetString("ActivityLog_User_createHackathonAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Became an admin of the hackathon..
        /// </summary>
        internal static string ActivityLog_User_createHackathonAdmin2 {
            get {
                return ResourceManager.GetString("ActivityLog_User_createHackathonAdmin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Added a new judge &apos;{judgeName}&apos;..
        /// </summary>
        internal static string ActivityLog_User_createJudge {
            get {
                return ResourceManager.GetString("ActivityLog_User_createJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Added an organizer &quot;{organizerName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_createOrganizer {
            get {
                return ResourceManager.GetString("ActivityLog_User_createOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is added as platform admin by user {operatorName}..
        /// </summary>
        internal static string ActivityLog_User_createPlatformAdmin {
            get {
                return ResourceManager.GetString("ActivityLog_User_createPlatformAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added user {userName} as platform admin..
        /// </summary>
        internal static string ActivityLog_User_createPlatformAdmin2 {
            get {
                return ResourceManager.GetString("ActivityLog_User_createPlatformAdmin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Rated team &quot;{teamName}&quot; on kind &quot;{kindName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_createRating {
            get {
                return ResourceManager.GetString("ActivityLog_User_createRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Created a new rating kind &apos;{ratingKind}&apos;..
        /// </summary>
        internal static string ActivityLog_User_createRatingKind {
            get {
                return ResourceManager.GetString("ActivityLog_User_createRatingKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Created a new team &apos;{teamName}&apos;..
        /// </summary>
        internal static string ActivityLog_User_createTeam {
            get {
                return ResourceManager.GetString("ActivityLog_User_createTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Added a new work for team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_createTeamWork {
            get {
                return ResourceManager.GetString("ActivityLog_User_createTeamWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Created a new template &quot;{templateName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_createTemplate {
            get {
                return ResourceManager.GetString("ActivityLog_User_createTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]deleted an announcement..
        /// </summary>
        internal static string ActivityLog_User_deleteAnnouncement {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Dismissed team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_deleteAward {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Revoked an assignment on award &quot;{awardName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_deleteAwardAssignment {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteAwardAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]An assignment on award &quot;{awardName}&quot; is revoked by &quot;{adminName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_deleteAwardAssignment2 {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteAwardAssignment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Deleted an experiment..
        /// </summary>
        internal static string ActivityLog_User_deleteExperiment {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Deleted hackathon..
        /// </summary>
        internal static string ActivityLog_User_deleteHackathon {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteHackathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Deleted an admin &apos;{adminName}&apos; from hackathon..
        /// </summary>
        internal static string ActivityLog_User_deleteHackathonAdmin {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteHackathonAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]No longer be an admin of the hackathon..
        /// </summary>
        internal static string ActivityLog_User_deleteHackathonAdmin2 {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteHackathonAdmin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Deleted judge &apos;{judgeName}&apos; of the hackathon..
        /// </summary>
        internal static string ActivityLog_User_deleteJudge {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Deleted an organizer &quot;{organizerName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_deleteOrganizer {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Removed a rating in hackathon..
        /// </summary>
        internal static string ActivityLog_User_deleteRating {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Deleted rating kind &quot;{ratingKind}&quot;..
        /// </summary>
        internal static string ActivityLog_User_deleteRatingKind {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteRatingKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Dismissed team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_deleteTeam {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Removed member &quot;{memberName}&quot; from team &quot;{teamName}&quot; or rejected the membership request..
        /// </summary>
        internal static string ActivityLog_User_deleteTeamMember {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Removed from team &quot;{teamName}&quot; by user &quot;{operatorName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_deleteTeamMember2 {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteTeamMember2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Deleted a team work from from team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_deleteTeamWork {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteTeamWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Deleted experiment template &quot;{templateName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_deleteTemplate {
            get {
                return ResourceManager.GetString("ActivityLog_User_deleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded a new file..
        /// </summary>
        internal static string ActivityLog_User_fileUpload {
            get {
                return ResourceManager.GetString("ActivityLog_User_fileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Requested to join team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_joinTeam {
            get {
                return ResourceManager.GetString("ActivityLog_User_joinTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Left team &quot;{memberName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_leaveTeam {
            get {
                return ResourceManager.GetString("ActivityLog_User_leaveTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successfully..
        /// </summary>
        internal static string ActivityLog_User_login {
            get {
                return ResourceManager.GetString("ActivityLog_User_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Requested to publish hackathon..
        /// </summary>
        internal static string ActivityLog_User_publishHackathon {
            get {
                return ResourceManager.GetString("ActivityLog_User_publishHackathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Rejected enrollment of user &quot;{enrolledUser}&quot;..
        /// </summary>
        internal static string ActivityLog_User_rejectEnrollment {
            get {
                return ResourceManager.GetString("ActivityLog_User_rejectEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Enrollment rejected by admin &quot;{adminName}&quot;.
        /// </summary>
        internal static string ActivityLog_User_rejectEnrollment2 {
            get {
                return ResourceManager.GetString("ActivityLog_User_rejectEnrollment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Reset the experiment &quot;{experiment}&quot;..
        /// </summary>
        internal static string ActivityLog_User_resetExperiment {
            get {
                return ResourceManager.GetString("ActivityLog_User_resetExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Updated hackathon as Writable..
        /// </summary>
        internal static string ActivityLog_User_unarchiveHackathon {
            get {
                return ResourceManager.GetString("ActivityLog_User_unarchiveHackathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]updated an announcement..
        /// </summary>
        internal static string ActivityLog_User_updateAnnouncement {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Updated the award &quot;{awardName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_updateAward {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Updated an assignment on award &quot;{awardName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_updateAwardAssignment {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateAwardAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Assignment on award &quot;{awardName}&quot; is updated by &quot;{adminName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_updateAwardAssignment2 {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateAwardAssignment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Enrollment info in hackathon &quot;{hackathonName}&quot; updated..
        /// </summary>
        internal static string ActivityLog_User_updateEnrollment {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Updated enrollment info of user &quot;{userName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_updateEnrollment2 {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateEnrollment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Updated hackathon..
        /// </summary>
        internal static string ActivityLog_User_updateHackathon {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateHackathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Updated judge &apos;{judgeName}&apos; for the hackathon..
        /// </summary>
        internal static string ActivityLog_User_updateJudge {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Updated organizer &quot;{organizerName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_updateOrganizer {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Updated a rating on kind &quot;{ratingKindName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_updateRating {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Updated rating kind &quot;{ratingKind}&quot;..
        /// </summary>
        internal static string ActivityLog_User_updateRatingKind {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateRatingKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Updated team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_updateTeam {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Updated the info of member &quot;{memberName}&quot; in team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_updateTeamMember {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Info of membership in team &quot;{teamName}&quot; is updated..
        /// </summary>
        internal static string ActivityLog_User_updateTeamMember2 {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateTeamMember2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Updated the role of team member &quot;{memberName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_updateTeamMemberRole {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateTeamMemberRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]User &quot;{adminName}&quot; updated your role in team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_updateTeamMemberRole2 {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateTeamMemberRole2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Updated a work of team &quot;{teamName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_updateTeamWork {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateTeamWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{hackathonName}]Updated the template &quot;{templateName}&quot;..
        /// </summary>
        internal static string ActivityLog_User_updateTemplate {
            get {
                return ResourceManager.GetString("ActivityLog_User_updateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creator of a hackathon cannot be deleted..
        /// </summary>
        internal static string Admin_CannotDeleteCreator {
            get {
                return ResourceManager.GetString("Admin_CannotDeleteCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user is not an admin of the hackathon.
        /// </summary>
        internal static string Admin_NotFound {
            get {
                return ResourceManager.GetString("Admin_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement is not found..
        /// </summary>
        internal static string Announcement_NotFound {
            get {
                return ResourceManager.GetString("Announcement_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden. The user associated with the token doesn&apos;t have proper permission. Please contact the administrator for access..
        /// </summary>
        internal static string Auth_Forbidden {
            get {
                return ResourceManager.GetString("Auth_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access token cannot be validated. Code:{0}, Message:{1}.
        /// </summary>
        internal static string Auth_Token_ValidateRemoteFailed {
            get {
                return ResourceManager.GetString("Auth_Token_ValidateRemoteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token expired at {0}. Please re-login..
        /// </summary>
        internal static string Auth_TokenExpired {
            get {
                return ResourceManager.GetString("Auth_TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is either missing or invalid. Please add it to Http request headers: Headers[&quot;Authorization&quot;]=token TOKEN. .
        /// </summary>
        internal static string Auth_Unauthorized {
            get {
                return ResourceManager.GetString("Auth_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The award is assigned hence cannot delete. Please delete the assignments first..
        /// </summary>
        internal static string Award_CannotDeleteAssigned {
            get {
                return ResourceManager.GetString("Award_CannotDeleteAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `award.target` cannot be updated since the award is already assigned to a team or user. Please delete the assignment(s) first..
        /// </summary>
        internal static string Award_CannotUpdateTarget {
            get {
                return ResourceManager.GetString("Award_CannotUpdateTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award with specified id is not found..
        /// </summary>
        internal static string Award_NotFound {
            get {
                return ResourceManager.GetString("Award_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A maximum of 100 awards are allowed..
        /// </summary>
        internal static string Award_TooMany {
            get {
                return ResourceManager.GetString("Award_TooMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign the award to more than {0} assignees..
        /// </summary>
        internal static string Award_TooManyAssignments {
            get {
                return ResourceManager.GetString("Award_TooManyAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assignment is not found..
        /// </summary>
        internal static string AwardAssignment_NotFound {
            get {
                return ResourceManager.GetString("AwardAssignment_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment already ended at {0}.
        /// </summary>
        internal static string Enrollment_Ended {
            get {
                return ResourceManager.GetString("Enrollment_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment cannot be fullfilled since it has reached the quota..
        /// </summary>
        internal static string Enrollment_Full {
            get {
                return ResourceManager.GetString("Enrollment_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment not approved yet. Please contact the hackathon admistrators for approval..
        /// </summary>
        internal static string Enrollment_NotApproved {
            get {
                return ResourceManager.GetString("Enrollment_NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} not enrolled in hackathon {1}.
        /// </summary>
        internal static string Enrollment_NotFound {
            get {
                return ResourceManager.GetString("Enrollment_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment not started. The enrollment will be accepted starting from {0}.
        /// </summary>
        internal static string Enrollment_NotStarted {
            get {
                return ResourceManager.GetString("Enrollment_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of extensions exceeds the allowed limit {0}..
        /// </summary>
        internal static string Enrollment_TooManyExtensions {
            get {
                return ResourceManager.GetString("Enrollment_TooManyExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The experiment is not found..
        /// </summary>
        internal static string Experiment_NotFound {
            get {
                return ResourceManager.GetString("Experiment_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden. The experiment is owned by another user..
        /// </summary>
        internal static string Experiment_UserNotMatch {
            get {
                return ResourceManager.GetString("Experiment_UserNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hackathon {0} is already Online..
        /// </summary>
        internal static string Hackathon_AlreadyOnline {
            get {
                return ResourceManager.GetString("Hackathon_AlreadyOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user created too many hackathons, please try again at a later time or contact the administrator..
        /// </summary>
        internal static string Hackathon_CreateTooMany {
            get {
                return ResourceManager.GetString("Hackathon_CreateTooMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hackathon is already ended at {0}.
        /// </summary>
        internal static string Hackathon_Ended {
            get {
                return ResourceManager.GetString("Hackathon_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hackathon is not allowed to delete since there are active award assignments. Please revoke the award assignments first..
        /// </summary>
        internal static string Hackathon_HasAwardAssignment {
            get {
                return ResourceManager.GetString("Hackathon_HasAwardAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is invalid. Must contain only letters and/or numbers, length between 1 and 100..
        /// </summary>
        internal static string Hackathon_Name_Invalid {
            get {
                return ResourceManager.GetString("Hackathon_Name_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is already used. Please try another name..
        /// </summary>
        internal static string Hackathon_Name_Taken {
            get {
                return ResourceManager.GetString("Hackathon_Name_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. Only the admins of the hackathon are allowed. Please contact the admin to request access..
        /// </summary>
        internal static string Hackathon_NotAdmin {
            get {
                return ResourceManager.GetString("Hackathon_NotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hackathon with name `{0}` not found. Try PUT to create a new one..
        /// </summary>
        internal static string Hackathon_NotFound {
            get {
                return ResourceManager.GetString("Hackathon_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. Only the judges of the hackathon are allowed. Please contact the admin to request access..
        /// </summary>
        internal static string Hackathon_NotJudge {
            get {
                return ResourceManager.GetString("Hackathon_NotJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested operation is not allowed since the hackathon is not online.
        /// </summary>
        internal static string Hackathon_NotOnline {
            get {
                return ResourceManager.GetString("Hackathon_NotOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hackathon is not started yet. .
        /// </summary>
        internal static string Hackathon_NotStarted {
            get {
                return ResourceManager.GetString("Hackathon_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hackathon is archived and is ReadOnly..
        /// </summary>
        internal static string Hackathon_ReadOnly {
            get {
                return ResourceManager.GetString("Hackathon_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected exception occurs. Please try again later or report an issue at https://github.com/kaiyuanshe/open-hackathon/issues.
        /// </summary>
        internal static string Hackathon_UnhandledException {
            get {
                return ResourceManager.GetString("Hackathon_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user is not judge of the hackathon..
        /// </summary>
        internal static string Judge_NotFound {
            get {
                return ResourceManager.GetString("Judge_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A maximum of 100 judges are allowed..
        /// </summary>
        internal static string Judge_TooMany {
            get {
                return ResourceManager.GetString("Judge_TooMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organizer is not found..
        /// </summary>
        internal static string Organizer_NotFound {
            get {
                return ResourceManager.GetString("Organizer_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required parameter {0} is null or empty..
        /// </summary>
        internal static string Parameter_Required {
            get {
                return ResourceManager.GetString("Parameter_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the {0}. Must delete related Rating first..
        /// </summary>
        internal static string Rating_HasRating {
            get {
                return ResourceManager.GetString("Rating_HasRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rating kind of specified Id doesn&apos;t exist..
        /// </summary>
        internal static string Rating_KindNotFound {
            get {
                return ResourceManager.GetString("Rating_KindNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rating is not found..
        /// </summary>
        internal static string Rating_NotFound {
            get {
                return ResourceManager.GetString("Rating_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. The rating is created by another person..
        /// </summary>
        internal static string Rating_OnlyCreator {
            get {
                return ResourceManager.GetString("Rating_OnlyCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The score must be not greater than {0}..
        /// </summary>
        internal static string Rating_ScoreNotInRange {
            get {
                return ResourceManager.GetString("Rating_ScoreNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A maximum of 100 rating kinds are allowed..
        /// </summary>
        internal static string Rating_TooManyKinds {
            get {
                return ResourceManager.GetString("Rating_TooManyKinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a new team since the user is already in a team..
        /// </summary>
        internal static string Team_CreateSecond {
            get {
                return ResourceManager.GetString("Team_CreateSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the team for awards are assigned to this team. Please delete the award assignments first..
        /// </summary>
        internal static string Team_HasAward {
            get {
                return ResourceManager.GetString("Team_HasAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team name &apos;{0}&apos; is already taken. Please try a different name..
        /// </summary>
        internal static string Team_NameTaken {
            get {
                return ResourceManager.GetString("Team_NameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is too long. Length cannot exceed 128..
        /// </summary>
        internal static string Team_NameTooLong {
            get {
                return ResourceManager.GetString("Team_NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. Please contact admins of the team..
        /// </summary>
        internal static string Team_NotAdmin {
            get {
                return ResourceManager.GetString("Team_NotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a new team. must enroll first..
        /// </summary>
        internal static string Team_NotEnrolled {
            get {
                return ResourceManager.GetString("Team_NotEnrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team with specified id is not found..
        /// </summary>
        internal static string Team_NotFound {
            get {
                return ResourceManager.GetString("Team_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user doesn&apos;t join a team. .
        /// </summary>
        internal static string Team_NotJoined {
            get {
                return ResourceManager.GetString("Team_NotJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member {0} is not allowed to perform this operation..
        /// </summary>
        internal static string TeamMember_AccessDenied {
            get {
                return ResourceManager.GetString("TeamMember_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is in a different team. Please leave the current team if want to change a team..
        /// </summary>
        internal static string TeamMember_CannotChangeTeam {
            get {
                return ResourceManager.GetString("TeamMember_CannotChangeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user cannot be removed since there are more than 1 members and the user is the only admin with admin access..
        /// </summary>
        internal static string TeamMember_LastAdmin {
            get {
                return ResourceManager.GetString("TeamMember_LastAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is not a member of team {1}.
        /// </summary>
        internal static string TeamMember_NotFound {
            get {
                return ResourceManager.GetString("TeamMember_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team work cannot be found..
        /// </summary>
        internal static string TeamWork_NotFound {
            get {
                return ResourceManager.GetString("TeamWork_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A maximum of 100 works are allowed..
        /// </summary>
        internal static string TeamWork_TooMany {
            get {
                return ResourceManager.GetString("TeamWork_TooMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create more than {0} templates in a hackathon..
        /// </summary>
        internal static string Template_ExceedMax {
            get {
                return ResourceManager.GetString("Template_ExceedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the template since it&apos;s being used by one or more experiments. Please delete the experiments first..
        /// </summary>
        internal static string Template_HasExperiment {
            get {
                return ResourceManager.GetString("Template_HasExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template `{0}` cannot be found in hackathon `{1}`..
        /// </summary>
        internal static string Template_NotFound {
            get {
                return ResourceManager.GetString("Template_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user is not found..
        /// </summary>
        internal static string User_NotFound {
            get {
                return ResourceManager.GetString("User_NotFound", resourceCulture);
            }
        }
    }
}
