using System.Collections.Generic;

namespace Kaiyuanshe.OpenHackathon.Server.Storage.Entities
{
    /// <summary>
    /// activity logs of user and hackathon
    /// PK: userId or hackathon name
    /// RK: Generated by <see cref="StorageUtils.InversedTimeKey(System.DateTime)"/> plus a random string from guid.
    /// </summary>
    public class ActivityLogEntity : BaseTableEntity
    {
        public string HackathonName { get; set; }

        /// <summary>
        /// Id of User who performs the operation.
        /// </summary>
        public string OperatorId { get; set; }

        /// <summary>
        /// auto-generated. RowKey.  Any input will be ignored.
        /// </summary>
        [IgnoreEntityProperty]
        public string ActivityId => RowKey;

        /// <summary>
        /// No need to specify for now.
        /// </summary>
        public ActivityLogCategory Category { get; set; }

        /// <summary>
        /// type of the activity log. <see cref="ActivityLogType"/>
        /// </summary>
        public string ActivityLogType { get; set; }

        /// <summary>
        /// ResourceKey to lookup resource files.
        /// </summary>
        public string MessageResourceKey { get; set; }

        /// <summary>
        /// Messages for all cultures. Use CultureInfo.Name as key.
        /// </summary>
        [ConvertableEntityProperty]
        public Dictionary<string, string> Messages { get; set; } = new();
    }

    public enum ActivityLogCategory
    {
        Hackathon,
        User,
        Team,
    }
}
