# This is a basic workflow to help you get started with Actions

name: .NET 6 Build, Push and Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
    - main
    paths:
    - src/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: "./src/open-hackathon-server"
    env:
      config: 'Release'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v3

    # Setup .Net
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.*

    # restore dependencies
    - name: Install dependencies
      run: dotnet restore

    # build project
    - name: Build
      run: dotnet build --configuration $config --no-restore

      # run tests with built project
    - name: Test
      run: dotnet test --no-restore --no-build --configuration $config

  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # https://github.com/docker/metadata-action#tags-input
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          openhackathon/oph-server-v2
          kysprodacr.azurecr.cn/oph-server-v2
        # generate Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=sha,format=long
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

    - name: Login to Azure Container Registry	
      uses: docker/login-action@v2
      with:	
        registry: kysprodacr.azurecr.cn	
        username: ${{ secrets.REGISTRY_USERNAME }}	
        password: ${{ secrets.REGISTRY_PASSWORD }}
      
    # https://github.com/docker/build-push-action#advanced-usage
    - name: Build and Push image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./src/deploy/hackathon-docker/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
  
    # test site
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'hackathon-api-test'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_TEST }}
        images: 'kysprodacr.azurecr.cn/oph-server-v2:sha-${{ github.sha }}'

    # prod
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'hackathon-api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'kysprodacr.azurecr.cn/oph-server-v2:sha-${{ github.sha }}'
