name: .NET Build - Pull Request

on:
  pull_request:
    branches: 
    - main
    paths:
    - src/**

defaults:
  run:
    shell: bash
    working-directory: "./src/open-hackathon-server"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      config: 'Release'
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.*
      
      # restore dependencies  
    - name: Install dependencies
      run: dotnet restore
      
      # build project
    - name: Build
      run: dotnet build --configuration $config --no-restore
      
      # set report file and title 
    - name: Set Test Title
      run: | 
            if ${{ github.event_name == 'pull_request' }}
            then
              echo "title=Test Run for PR #${{github.event.number}} (${{github.run_id}})" >> $GITHUB_ENV
              echo "file_name=TestReport.pr.${{github.run_id}}.md" >> $GITHUB_ENV
            else
              echo "title=Test Run ${{github.run_id}}" >> $GITHUB_ENV
              echo "file_name=TestReport.${{github.run_id}}.md" >> $GITHUB_ENV
            fi
      
      # run tests with built project
    - name: run Unit Tests
      run: dotnet test --no-restore --no-build --configuration $config --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}};Title=${{env.title}};"
      
      # upload report as build artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: 'testresult'
        path: ${{github.workspace}}/${{env.file_name}}
